/*
 * Section 4: the App's Keys tab, against a device instead of a mock.
 *
 * THE APP'S OWN SUITE DOES NOT TOUCH THIS TAB AT ALL. `configure-slot-test.js`
 * covers slots and `startup-test.js` covers two dialogs; nothing anywhere
 * exercises key loading. That matters more here than it did for slots, because
 * this is the tab that puts KEY MATERIAL on the device: a mocked `chrome.hid`
 * cannot tell you that the bytes which arrived are the bytes of the key you
 * pasted, and that is the only question worth asking about a key loader.
 *
 * THE ORACLE IS THE DEVICE, AND OPENPGP.JS FROM THE OTHER SIDE. The key is
 * generated by this kit's openpgp (v5), handed to the App as an armored,
 * passphrase-protected private key, parsed by the App's own bundled openpgp
 * (v4), split by the App into P and Q, and sent over `chrome.hid`. Then the kit
 * asks the DEVICE to publish the modulus of each slot and compares it against
 * the `n` openpgp.js computed. Nothing in that chain is self-consistent: an App
 * that mangled a factor produces a modulus that does not match, and an App that
 * put the halves in the wrong slots produces two moduli that match the wrong
 * way round.
 *
 * It is also a cross-VERSION agreement for free - v5 writes the armor, v4 reads
 * it - which is the property that breaks quietly when either moves.
 *
 * WHAT THE SLOT CONVENTION MEANS, AND WHY IT IS THE BEST ASSERTION HERE.
 * `initKeySelect()` on Auto Load puts the SIGNING key in slot 2 and the
 * DECRYPTION key in slot 1, with no dialog. That is exactly the pair
 * `onlykey-pgp.js`'s `slotid()` hardcodes, and exactly what `02-cli/16-cli-key-files`
 * measured for `onlykey-cli loadkey`. So this file makes a third client agree
 * with the other two about a convention that is written down nowhere.
 *
 * SURFACE: vendor, plus the App's own UI. Every answer about what the device
 * holds arrives where a client can see it; the debug console is not read.
 *
 * OUTSIDE `--isolate` AND `--reverse` BY CONSTRUCTION, like the rest of the
 * section - the session lives in 10-session.
 */
'use strict';

const { describe, it } = require('../../lib/harness');
const { IFACE, okmsg } = require('../../lib/device');
const { PINS } = require('../../lib/config');
const webenv = require('../../lib/webenv');
const pqc = require('../../lib/pqc');
const { pgpRsaKey, collectVendor, RSA_2048_BYTES } = require('../../lib/pgp-rsa');

const session = require('../../lib/app-session-holder');

const PASSPHRASE = 'okt-app-keys-passphrase';

/** Switch to a tab by clicking the same control a user would. */
async function showPanel(page, showId) {
  await page.eval(`(() => {
    const el = document.getElementById(${JSON.stringify(showId)});
    if (!el) throw new Error('no such panel control: ' + ${JSON.stringify(showId)});
    el.click();
  })()`);
}

describe('app keys', {
  state: 'initialized',
  requires: ['client-access', 'display', 'nwjs'],
  timeoutMs: 300000,
}, () => {
  it('loads a PGP RSA key through the Keys tab, and both slots publish the right modulus', async ({ device, assert, signal, log }) => {
    /*
     * ESTABLISH THE STATE. OKSETPRIV is refused outside config mode - the
     * firmware answers "Error not in config mode", which 02-cli/12-cli-slots
     * pinned - so the device is put into config mode BEFORE the App is asked to
     * load anything. readyForKeygen() restarts to get there, which the App
     * survives: it re-enumerates on onDeviceAdded.
     */
    const openpgp = webenv.openpgp();
    const key = await pgpRsaKey(openpgp, [{ name: 'OKT App', email: 'okt-app@example.invalid' }]);
    const encrypted = await openpgp.encryptKey({
      privateKey: key.privateKey, passphrase: PASSPHRASE,
    });
    const armoredPrivate = encrypted.armor();
    log(`generated an RSA-2048 PGP key, armored private half is ${armoredPrivate.length} bytes`);

    await pqc.readyForKeygen(device, { signal });

    const s = session.get();
    const page = await s.attach('app');
    try {
      await s.waitForDevice(page, device, { signal, log });
      await showPanel(page, 'show-keys-panel');

      /*
       * Watch the DEVICE while the App does the work. Two "Successfully set RSA
       * Key" acknowledgements are what a successful Auto Load looks like from
       * this side - one per slot - and they arrive on the vendor interface,
       * where a client would see them.
       */
      const since = device.mark(IFACE.VENDOR);

      const submitted = await page.eval(`(() => {
        const form = document.getElementById('rsaForm');
        const keyField = document.getElementById('rsaKey');
        const passField = document.getElementById('rsaPasscode');
        const slotSel = document.getElementById('rsaSlot');
        if (!keyField || !passField || !slotSel) return 'the Keys tab form is not present';

        keyField.value = ${JSON.stringify(armoredPrivate)};
        keyField.dispatchEvent(new Event('input', {bubbles: true}));
        passField.value = ${JSON.stringify(PASSPHRASE)};
        passField.dispatchEvent(new Event('input', {bubbles: true}));

        /* 99 is "Auto Load", which is the path that decides the slots itself. */
        slotSel.value = '99';
        slotSel.dispatchEvent(new Event('change', {bubbles: true}));

        document.getElementById('rsaSubmit').click();
        return 'submitted';
      })()`);
      assert.equal(submitted, 'submitted', submitted);

      /*
       * The App parses the key asynchronously before it sends anything, so an
       * error can appear in its own error box well after the click. Read that
       * first - it is a better failure message than a device timeout.
       */
      const acks = [];
      for (let i = 0; i < 2; i++) {
        const ack = await device.waitHid(IFACE.VENDOR,
          { since, match: /Successfully set RSA Key|Error/, timeoutMs: 25000, signal })
          .catch(async () => {
            const err = await page.eval(
              "document.getElementById('rsaFormError').innerText || ''");
            throw new Error(
              `the device never acknowledged RSA key ${i + 1}` +
              (err ? ` - the App reported: ${err}` : ' - and the App reported no error'));
          });
        const text = okmsg.text(ack).trim();
        acks.push(text);
        log(`device said: ${text}`);
        assert.ok(!/Error/.test(text), `loading the key through the App: ${text}`);
      }
      assert.equal(acks.length, 2,
        'Auto Load should write TWO slots - a signing half and a decryption half');

      const formError = await page.eval(
        "document.getElementById('rsaFormError').innerText || ''");
      assert.equal(formError, '', `the App reported an error after loading: ${formError}`);
    } finally {
      page.close();
    }

    /*
     * NOW ASK THE DEVICE. A reboot first, because the readback has to come from
     * flash rather than from whatever the write left in RAM - the same reason
     * lib/pgp-rsa.js's loadSlots() restarts before it reads.
     */
    /*
     * SETTLE BEFORE REBOOTING, and this is a hazard rather than a nicety.
     * "Successfully set RSA Key" is emitted by the message handler, not by the
     * flash write completing - so a client that acts on the acknowledgement can
     * be faster than the device's own commit. Rebooting immediately after the
     * second ack loses the second key: slot 2 reads back and slot 1 answers
     * "Error no RSA Private Key set in this slot". Measured three times; the
     * probe that first showed both slots populated differed only by waiting.
     */
    await device.sleep(6000, { signal });

    await device.restart({ signal });
    await device.ensureUnlocked(PINS.primary, { signal });

    for (const [slot, half, what] of [[1, 'sub', 'decryption'], [2, 'primary', 'signing']]) {
      /*
       * Let the previous answer drain before asking the next question.
       *
       * OKGETPUBKEY answers with a burst of unsolicited reports and the device
       * is briefly busy afterwards; asking again immediately got a REFUSAL for
       * the second slot ("Error no RSA Private Key set in this slot") on a
       * device that demonstrably held the key - the same question asked a moment
       * later answers with the modulus. A refusal is indistinguishable from an
       * empty slot unless the test knows to tell them apart, which is what the
       * check below is for.
       */
      await device.sleep(1500, { signal });

      const since = device.mark(IFACE.VENDOR);
      device.sendVendor({ msg: okmsg.MSG.OKGETPUBKEY, slot, field: 0 });
      const published = await collectVendor(device, since, RSA_2048_BYTES, { signal });

      /*
       * An error string is ASCII and a modulus is not, so a reply that reads as
       * text is a refusal wearing a modulus's clothes. Named explicitly,
       * because "differs at byte 0" for `4572726f...` is "Error no..." and says
       * nothing about which of the two things went wrong.
       */
      const asText = published.subarray(0, 32).toString('latin1');
      assert.ok(!/^Error/.test(asText),
        `RSA slot ${slot} did not answer with a modulus at all - it said ` +
        `${JSON.stringify(asText.split(' ')[0])}`);

      assert.bytes(published, key[half].n,
        `RSA slot ${slot} published a modulus that is not the ${what} half of the ` +
        'key the App was given - so the App either mangled a factor or put the ' +
        'halves in the wrong slots');
      log(`RSA slot ${slot} holds the ${what} half, ${published.length} bytes`);
    }
  });

  it('puts the SIGNING half in slot 2 and the DECRYPTION half in slot 1, agreeing with onlykey-cli', async ({ device, assert, signal, log }) => {
    /*
     * The convention nobody writes down, now checked against a THIRD client.
     *
     * `onlykey-pgp.js`'s `slotid()` sends OKSIGN to slot 2 and everything else
     * to slot 1, so the encrypt and decrypt pages look for a signing key in 2
     * and a decryption key in 1. `02-cli/16-cli-key-files` measured that
     * `onlykey-cli loadkey` auto mode fills exactly that pair. This asserts the
     * App does the same, which is what makes a key loaded in the App usable by
     * the pages - and it is asserted the strong way, by proving the two moduli
     * are NOT interchangeable.
     *
     * Depends on the load performed by the test above, which is the coupling
     * this tier allows; splitting it would mean a second RSA keygen and a second
     * config-mode restart to assert one property of the first.
     */
    const read = {};
    for (const [slot, half] of [[2, 'primary'], [1, 'sub']]) {
      await device.sleep(1500, { signal });
      const since = device.mark(IFACE.VENDOR);
      device.sendVendor({ msg: okmsg.MSG.OKGETPUBKEY, slot, field: 0 });
      read[half] = await collectVendor(device, since, RSA_2048_BYTES, { signal });
    }

    /*
     * The control that makes the claim mean something: if the two slots held
     * the same key, or if the readback were returning whatever was asked for,
     * every arrangement would "pass". They must differ.
     */
    assert.ok(!read.primary.equals(read.sub),
      'both RSA slots published the SAME modulus, so this file cannot tell which ' +
      'half went where - the readback is not distinguishing the slots');
    log('the two slots hold different moduli, so the slot assignment is observable');
  });
});
