/*
 * The derived X-Wing split-custody maths, against a vector python computed.
 *
 * This is the carried-over 05-age-pqc-derived, and the reason the sanity
 * section exists at all: no device, no binaries, no kernel node - the kit's own
 * arithmetic checked against a known answer before anything trusts it.
 *
 * Split custody means the secret is never in one place. The device holds sk_X
 * and returns only ss_X = X25519(sk_X, ct_X) plus a one-way ML-KEM seed; the
 * host expands the seed, decapsulates ct_M, and combines. Neither half can
 * decrypt on its own, which is the property the last test here checks by
 * withholding the device's half.
 *
 * The first five tests are self-consistency - they would all pass against a JS
 * port that had drifted, as long as it had drifted consistently. The sixth is
 * the one with teeth: a vector generated by python-onlykey's OWN
 * derived_xwing.py on fixed inputs (tools/gen-derived-xwing-vector.py), so it
 * proves this file agrees with what age-plugin-onlykey actually computes rather
 * than merely with itself. Three implementations have to produce the same
 * bytes - this one, the CLI's, and the firmware's okcrypto_xwing_web_derive() -
 * and when they do not, the symptom is "decryption failed" with no hint which
 * one is wrong.
 *
 * deviceDerive() below stands in for a device, exactly as the Python test's
 * _device_derive() does. Doing this over the real WebAuthn tunnel is later
 * work, and it is 10-fido2-xwing-derive; pinning the maths here first is what
 * will make that debuggable, because a mismatch then can only be the device.
 */
'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const { describe, it } = require('../../lib/harness');
const pqc = require('../../lib/age-pqc');

const VECTOR = path.join(__dirname, 'fixtures', 'derived-xwing-vector.json');

describe('derived X-Wing split custody', {
  device: false,
  requires: ['xwing-math'],
}, () => {
  /* What a device would hand back, minus the device. */
  function deviceDerive() {
    const skX = pqc.x25519Secret();
    return { skX, pkX: pqc.x25519Base(skX), mlkemSeed: crypto.randomBytes(32) };
  }

  it('a recipient is pk_M then pk_X, 1216 bytes', async ({ assert }) => {
    const { pkX, mlkemSeed } = deviceDerive();
    const recipient = pqc.buildRecipient(pkX, mlkemSeed);

    assert.equal(recipient.length, pqc.XWING_PK);
    assert.bytes(recipient.subarray(pqc.MLKEM_PK), pkX,
      'pk_X sits at the END of the recipient, not the start');
  });

  it('split decapsulation lands on the same secret as a plain encapsulation',
    async ({ assert }) => {
      const { skX, pkX, mlkemSeed } = deviceDerive();
      const recipient = pqc.buildRecipient(pkX, mlkemSeed);

      /* The sender's side, which knows nothing about any of this. */
      const { sharedSecret: ssEnc, ciphertext: ct } = pqc.xwingEncapsHost(recipient);
      assert.equal(ct.length, pqc.XWING_CT);

      const ssX = pqc.x25519Shared(skX, pqc.ctXOf(ct));   // the device's half
      const ssDec = pqc.splitDecapsulate(ssX, ct, pkX, mlkemSeed);   // the host's

      assert.bytes(ssDec, ssEnc, 'split decapsulation');
    });

  it('no device share, no plaintext', async ({ assert }) => {
    /*
     * The security claim, stated as a test: without ss_X the combiner produces
     * an unrelated secret rather than a near miss, because ss_X is one of its
     * five bound inputs. This is what makes the key material on the device
     * load-bearing instead of ceremonial.
     */
    const { pkX, mlkemSeed } = deviceDerive();
    const recipient = pqc.buildRecipient(pkX, mlkemSeed);
    const { sharedSecret: ssEnc, ciphertext: ct } = pqc.xwingEncapsHost(recipient);

    const withoutDevice = pqc.splitDecapsulate(new Uint8Array(32), ct, pkX, mlkemSeed);

    assert.notEqual(Buffer.compare(Buffer.from(withoutDevice), Buffer.from(ssEnc)), 0,
      'a zero ss_X must not decapsulate');
  });

  it('the same seed always expands to the same recipient', async ({ assert }) => {
    /*
     * Not a formality. The device stores no ML-KEM key - it re-derives the seed
     * every time - so an expansion with any randomness in it would hand out a
     * different public key on every call and quietly break every identity ever
     * published from this device.
     */
    const { pkX, mlkemSeed } = deviceDerive();
    assert.bytes(pqc.buildRecipient(pkX, mlkemSeed), pqc.buildRecipient(pkX, mlkemSeed));
  });

  it('a derived identity carries its label and nothing else', async ({ assert }) => {
    for (const label of ['age:personal', 'alice@example.com', 'work']) {
      const identity = pqc.encodeIdentity(label);
      assert.ok(identity.startsWith(pqc.DERIVED_PREFIX), `${identity} is a derived identity`);

      const back = pqc.decodeIdentity(identity);
      assert.equal(back.derived, true);
      assert.equal(back.label, label, 'the label survives the round trip');
    }

    /* A slot identity is a different thing and must not decode as this one. */
    assert.equal(pqc.decodeIdentity('AGE-PLUGIN-ONLYKEY-1QQQ'), null,
      'a slot identity is not a derived identity');
  });

  it('matches python-onlykey byte for byte, on a fixed vector', async ({ assert }) => {
    const v = JSON.parse(fs.readFileSync(VECTOR, 'utf8'));
    const b64 = (s) => Buffer.from(s, 'base64');

    const pkX = b64(v.pk_x);
    const mlkemSeed = b64(v.mlkem_seed);

    /* Every step separately, so a failure names WHICH one diverged. */
    const { publicKey: pkM } = pqc.mlkemKeypairFromSeed(mlkemSeed);
    assert.bytes(pkM, b64(v.pk_m), 'ML-KEM public key from the seed');

    assert.bytes(pqc.buildRecipient(pkX, mlkemSeed), b64(v.recipient), 'recipient');

    assert.bytes(pqc.ctXOf(b64(v.ciphertext)), b64(v.ct_x),
      'ct_X, the slice the device is given');

    assert.bytes(
      pqc.splitDecapsulate(b64(v.ss_x), b64(v.ciphertext), pkX, mlkemSeed),
      b64(v.shared_secret),
      'the combined shared secret'
    );
  });
});
