/*
 * The web app's X-Wing maths, against the same fixed vector everything else is
 * checked against. No device, no browser, no display - `device: false`, so the
 * runner never starts a device host for it.
 *
 * There are now FOUR implementations of this arithmetic that have to agree:
 *
 *   python-onlykey's derived_xwing.py   what age-plugin-onlykey computes
 *   lib/age-pqc.js                      this kit's port, checked in 00-sanity
 *   onlykey-fido2's age_pqc.js          what the web app computes
 *   okcrypto.cpp's okcrypto_xwing_*     what the device computes
 *
 * The first three are checked here against one vector generated by the first.
 * The fourth is checked by section 2 decrypting a real age file. A mismatch
 * anywhere in that chain has exactly one symptom, "no identity matched any of
 * the recipients", and no indication of which link broke - which is the whole
 * reason to pin each link separately.
 *
 * This test is also how the kit found that its own identity encoding was stale.
 * lib/age-pqc.js carried `AGE-PLUGIN-ONLYKEY-DERIVED-` plus base32 - superseded,
 * and rejected by `age` - and a round-trip test could never have caught it,
 * because a wrong encoder and its matching decoder agree perfectly.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const { describe, it } = require('../../lib/harness');
const ours = require('../../lib/age-pqc');
const webenv = require('../../lib/webenv');

const VECTOR = path.join(__dirname, '..', '00-sanity', 'fixtures', 'derived-xwing-vector.json');

describe('the web app\'s X-Wing maths', {
  device: false,
  requires: ['xwing-math', 'webapp-lib'],
}, () => {
  const theirs = () => webenv.loadPlain('age_pqc.js');
  const vector = () => JSON.parse(fs.readFileSync(VECTOR, 'utf8'));
  const b64 = (s) => Buffer.from(s, 'base64');

  it('runs the same @noble build the web app ships', async ({ assert, log }) => {
    /*
     * This has to be checked, not assumed, and the reason is subtle enough to
     * write down.
     *
     * The web app does not npm-install @noble - it VENDORS it, at
     * onlykey/vendor/@noble, and webpack aliases the bare specifiers onto that
     * directory. webenv.loadPlain() replicates the alias, but only partly
     * survives: the vendored packages are ESM, and @noble/post-quantum imports
     * @noble/hashes by bare specifier internally, which Node's ESM resolver has
     * no alias for. So hashes and curves load from the app's own vendor tree
     * and post-quantum falls back to the copy installed here.
     *
     * That fallback is only harmless while the two are the same build. If the
     * app ever vendors a different @noble, every test below would keep passing
     * while silently testing this kit against itself.
     */
    for (const { name, vendored, ours } of webenv.vendoredVersions()) {
      log(`${name}: vendored ${vendored}, installed ${ours}`);
      assert.ok(vendored, `${name} is not vendored in the web app`);
      assert.equal(ours, vendored,
        `${name} differs between the web app and this kit - the parity below ` +
        'would be this kit checking itself');
    }
  });

  it('expands the device seed to the same ML-KEM key', async ({ assert }) => {
    const v = vector();
    const { publicKey } = theirs().mlkemKeypairFromSeed(b64(v.mlkem_seed));

    assert.bytes(publicKey, b64(v.pk_m), 'pk_M from the web app');
  });

  it('builds the same recipient', async ({ assert }) => {
    const v = vector();
    const recipient = theirs().buildRecipient(b64(v.pk_x), b64(v.mlkem_seed));

    assert.bytes(recipient, b64(v.recipient), 'the web app\'s recipient');
    assert.bytes(recipient, ours.buildRecipient(b64(v.pk_x), b64(v.mlkem_seed)),
      'the web app and this kit disagree');
  });

  it('completes the same split decapsulation', async ({ assert }) => {
    /*
     * The one that matters: the host half of a secret the device holds the
     * other half of. If these two disagree, a file encrypted in the browser
     * cannot be decrypted by the CLI and vice versa, with both sides certain
     * they are right.
     */
    const v = vector();
    const args = [b64(v.ss_x), b64(v.ciphertext), b64(v.pk_x), b64(v.mlkem_seed)];

    assert.bytes(theirs().splitDecapsulate(...args), b64(v.shared_secret),
      'the web app\'s shared secret');
    assert.bytes(theirs().splitDecapsulate(...args), ours.splitDecapsulate(...args),
      'the web app and this kit disagree');
  });

  it('encodes recipients and identities the same way', async ({ assert }) => {
    const v = vector();
    const lib = theirs();

    assert.equal(lib.encodeRecipient(b64(v.recipient)), v.recipient_for_vector,
      'the web app\'s recipient encoding');
    assert.equal(lib.encodeRecipient(b64(v.recipient)),
      ours.encodeRecipient(b64(v.recipient)),
      'the web app and this kit encode recipients differently');

    for (const [label, expected] of Object.entries(v.identities)) {
      assert.equal(lib.encodeIdentity(label), expected,
        `the web app's identity for ${JSON.stringify(label)}`);
      assert.equal(lib.encodeIdentity(label), ours.encodeIdentity(label),
        'the web app and this kit encode identities differently');
    }
  });

  it('derives the same label tag', async ({ assert }) => {
    /*
     * deriveLabelTag has no equivalent in this kit - it is the browser side of
     * the web-derivation request, hashing the label into the 32 bytes the
     * device is asked to derive from. Nothing here can cross-check it yet, so
     * this pins its shape and its determinism, which is what a later test
     * against the device will need to have been true.
     */
    const lib = theirs();
    if (typeof lib.deriveLabelTag !== 'function') {
      assert.ok(false, 'the web app no longer exports deriveLabelTag');
    }

    const tag = lib.deriveLabelTag('age:personal');
    assert.equal(tag.length, 32, 'a label tag is 32 bytes');
    assert.bytes(lib.deriveLabelTag('age:personal'), tag, 'the same label, twice');

    const other = lib.deriveLabelTag('work');
    assert.notEqual(Buffer.compare(Buffer.from(tag), Buffer.from(other)), 0,
      'two labels produced the same tag');
  });
});
