/*
 * Section 3, headless: derived X-Wing split custody, end to end, with a device.
 *
 * This closes a loop the other files only reach the ends of.
 * 01-age-pqc-parity pins the ARITHMETIC against a fixed vector but stands in for
 * the device with locally generated bytes; section 2 proves the whole thing
 * through `age` but only for a key STORED in a slot. This is the derived path -
 * nothing stored, the key reproduced on demand from (web-derivation key, label,
 * RPID) - and it is the one the web app's age-derive page uses.
 *
 * The round trip is the point, and every step is a different party:
 *
 *   1. the DEVICE derives pk_X and an ML-KEM seed for a label
 *   2. the HOST expands the seed and builds the 1216-byte recipient
 *   3. a SENDER encapsulates to that recipient - no device involved at all
 *   4. the DEVICE computes ss_X from ct_X, and never sees ct_M
 *   5. the HOST finishes decapsulation and must land on the sender's secret
 *
 * If step 5 agrees, then the firmware's okcrypto_xwing_web_derive(), the web
 * app's maths and this kit's port are all consistent - which is a stronger
 * statement than any of them checked alone, and the one thing that would
 * otherwise only surface as "no identity matched any of the recipients".
 *
 * The device never emits sk_X or the ML-KEM secret key. That is not a detail of
 * the implementation, it is the property being tested: the last test withholds
 * the device's half and requires the answer to be wrong.
 */
'use strict';

const { describe, it } = require('../../lib/harness');
const { PINS } = require('../../lib/config');
const { IFACE, okmsg } = require('../../lib/device');
const ours = require('../../lib/age-pqc');
const webenv = require('../../lib/webenv');

/* See 02-derive: the device refuses a touch-free derivation without this, and
 * says so as CTAP2_ERR_EXTENSION_NOT_SUPPORTED. */
const FIELD_DERIVED_KEY_MODE = 21;
const DERIVE_WITHOUT_TOUCH = 8;
const NO_PRESS = false;

const LABEL = 'age:personal';

describe('derived X-Wing, through the web app\'s library', {
  state: 'initialized',
  requires: ['crypto', 'xwing-math', 'webapp-lib'],
  timeoutMs: 90000,
}, () => {
  let third = null;

  const verbose = () => (process.env.OKT_WEBLIB_VERBOSE === 'yes' ? console : undefined);

  /* Unlike the derive pair in 02, these two always call back - they wrap
   * themselves in try/catch - so a plain promise is honest here. */
  const recipientFor = (label) => new Promise((resolve, reject) => {
    third.derive_xwing_recipient(label, NO_PRESS, (err, pkX, seed) => (
      err ? reject(new Error(String(err))) : resolve({ pkX, seed })
    ));
  });

  const decapFor = (label, ctX) => new Promise((resolve, reject) => {
    third.derive_xwing_decap(label, ctX, NO_PRESS, (err, ssX) => (
      err ? reject(new Error(String(err))) : resolve(ssX)
    ));
  });

  it('allows derivation without a touch', async ({ device, assert, signal }) => {
    await device.unlock(PINS.primary, { signal });
    await device.enterConfigMode(PINS.primary, { signal });

    const since = device.mark(IFACE.VENDOR);
    device.sendVendor({
      msg: okmsg.MSG.OKSETSLOT,
      slot: 1,
      field: FIELD_DERIVED_KEY_MODE,
      payload: String(DERIVE_WITHOUT_TOUCH),
    });

    const reply = await device.waitHid(IFACE.VENDOR,
      { since, match: /Successfully set|Error/, timeoutMs: 5000, signal });
    assert.ok(!/Error/.test(okmsg.text(reply)),
      `setting the derived-key mode failed: ${okmsg.text(reply)}`);

    await device.restart({ signal });
    await device.unlock(PINS.primary, { signal });

    const imports = webenv.create(device, { signal, console: verbose() });
    const api = webenv.load(imports, 'onlykey-api.js');
    third = webenv.load(imports, 'onlykey-3rd-party.js', api)();
  });

  it('derives a recipient for a label', async ({ assert, log }) => {
    const { pkX, seed } = await recipientFor(LABEL);
    log(`pk_X ${Buffer.from(pkX).toString('hex').slice(0, 24)}…`);

    assert.equal(Buffer.from(pkX).length, 32, 'pk_X is 32 bytes');
    assert.equal(Buffer.from(seed).length, 32, 'the ML-KEM seed is 32 bytes');

    /* Neither half may be the zeroes a failed derivation would leave. */
    assert.notEqual(Buffer.compare(Buffer.from(pkX), Buffer.alloc(32)), 0,
      'the device returned an all-zero pk_X');
    assert.notEqual(Buffer.compare(Buffer.from(seed), Buffer.alloc(32)), 0,
      'the device returned an all-zero seed');
  });

  it('derives the same key for the same label, and a different one for another',
    async ({ assert }) => {
      /*
       * The whole premise of the derived path: nothing is stored, so an
       * identity is only usable because the same label reproduces it. And two
       * labels must not collide, or every "separate" identity would be one.
       */
      const first = await recipientFor(LABEL);
      const again = await recipientFor(LABEL);
      assert.bytes(again.pkX, first.pkX, 'pk_X for the same label');
      assert.bytes(again.seed, first.seed, 'the seed for the same label');

      const other = await recipientFor('work');
      assert.notEqual(Buffer.compare(Buffer.from(other.pkX), Buffer.from(first.pkX)), 0,
        'two labels derived the same pk_X');
    });

  it('completes a split-custody round trip', async ({ assert, log }) => {
    /*
     * The one that matters. The sender encapsulates to the recipient with no
     * device present; the device then contributes exactly one X25519 shared
     * secret, computed from ct_X alone; and the host finishes. ct_M never
     * leaves the host and sk_X never leaves the device.
     */
    const { pkX, seed } = await recipientFor(LABEL);
    const recipient = ours.buildRecipient(Buffer.from(pkX), Buffer.from(seed));
    assert.equal(recipient.length, ours.XWING_PK, 'the recipient is 1216 bytes');

    const { sharedSecret, ciphertext } = ours.xwingEncapsHost(recipient);
    assert.equal(ciphertext.length, ours.XWING_CT, 'the ciphertext is 1120 bytes');

    const ctX = ours.ctXOf(ciphertext);
    const ssX = await decapFor(LABEL, Buffer.from(ctX));
    log(`ss_X ${Buffer.from(ssX).toString('hex').slice(0, 24)}…`);
    assert.equal(Buffer.from(ssX).length, 32, 'ss_X is 32 bytes');

    const recovered = ours.splitDecapsulate(
      Buffer.from(ssX), ciphertext, Buffer.from(pkX), Buffer.from(seed)
    );
    assert.bytes(recovered, sharedSecret,
      'the device\'s half did not complete the sender\'s secret');
  });

  it('the web app\'s own maths reaches the same secret', async ({ assert }) => {
    /*
     * Same round trip, but finished with the library the browser actually runs
     * rather than this kit's port. Both have now been checked against python's
     * fixed vector in 01-age-pqc-parity; this checks them against a real
     * device, which that file could not do.
     */
    const lib = webenv.loadPlain('age_pqc.js');
    const { pkX, seed } = await recipientFor(LABEL);

    const recipient = lib.buildRecipient(Buffer.from(pkX), Buffer.from(seed));
    const { sharedSecret, ciphertext } = lib.xwingEncapsHost(recipient);
    const ssX = await decapFor(LABEL, Buffer.from(lib.ctXOf(ciphertext)));

    const recovered = lib.splitDecapsulate(
      Buffer.from(ssX), ciphertext, Buffer.from(pkX), Buffer.from(seed)
    );
    assert.bytes(recovered, sharedSecret, 'the web app could not finish its own decapsulation');
  });

  it('cannot be finished without the device', async ({ assert }) => {
    /*
     * The security claim, stated as a test. Everything except ss_X is on the
     * host - the recipient, the ciphertext, the seed - so if the maths could be
     * completed from those alone, the device would be decoration.
     */
    const { pkX, seed } = await recipientFor(LABEL);
    const recipient = ours.buildRecipient(Buffer.from(pkX), Buffer.from(seed));
    const { sharedSecret, ciphertext } = ours.xwingEncapsHost(recipient);

    const withoutDevice = ours.splitDecapsulate(
      new Uint8Array(32), ciphertext, Buffer.from(pkX), Buffer.from(seed)
    );

    assert.notEqual(
      Buffer.compare(Buffer.from(withoutDevice), Buffer.from(sharedSecret)), 0,
      'the shared secret was recovered without the device\'s half'
    );
  });
});
