/*
 * Section 3, headless: the classic (non-PQC) PGP pages, at the LIBRARY tier.
 *
 * `/app/encrypt` and `/app/decrypt` are the two pages no kit has ever driven,
 * and this is the half of them that needs no browser: `onlykeyApi.pgp().api()`'s
 * startEncryption/startDecryption, called exactly the way encrypt.js and
 * decrypt.js call them, with `navigator.credentials.get` pointed at
 * lib/device/ctap2.js instead of at a browser's WebAuthn stack.
 *
 * That ordering is the whole reason section 3 is split at the file number: a
 * failure HERE is the library, and only once this passes does a failure in
 * nw.js mean the PAGE. The device half is not the variable either -
 * 01-protocol/23-rsa-tunnel already drives OKSIGN and OKDECRYPT over this exact
 * transport and checks both against node:crypto - so what is left uncovered
 * between the proven firmware and the unproven page is precisely this file.
 *
 * WHY THE KEY IS BUILT THE WAY IT IS. `onlykey-pgp.js`'s `slotid()` hardcodes
 * two RSA slots - `slot == OKSIGN ? 2 : 1` - so the pages can only ever use
 * RSA slot 2 to sign and RSA slot 1 to decrypt. A PGP key is a primary that
 * signs plus a subkey that encrypts, so ONE generated key supplies both: its
 * primary P||Q goes into slot 2 and its subkey's into slot 1. Nothing here
 * reaches for `onlykey-cli` - a classic RSA key goes in over the vendor
 * interface with OKSETPRIV, which is why this row carries no section-2
 * prerequisite even though the PQC page does.
 *
 * The key is generated by openpgp.js and the device is given its factors, which
 * is what makes the ORACLE independent: the message the library produces is
 * handed back to openpgp.js, which knows the same key from the other side and
 * has never heard of this device. A signature it verifies is a signature any
 * correspondent would verify, and a message it cannot open is one nobody could.
 *
 * SURFACES - see PRODUCTION.md. Every device operation rides the FIDO interface
 * and every key setup and modulus readback rides the vendor interface, so all of
 * that survives into a production walk. The console is read for two things no
 * client surface reports: WHEN a confirmation has primed, and WHICH bytes the
 * device hashed to pick the challenge digits. The second is also this file's
 * second oracle - the library prints the digits it computed, the device prints
 * the bytes it computed them from, and the two are required to agree. The first
 * two tests reach no device at all, which is their assertion rather than a gap.
 *
 * Every test brings the device to the state it needs itself, so the four that
 * need a key each pay for their own load - about thirty seconds. That is
 * deliberate: `--isolate` is a gate, and a file whose first test loads the key is
 * a file where no single mode can be debugged alone.
 */
'use strict';

const { describe, it } = require('../../lib/harness');
const { PINS } = require('../../lib/config');
const { IFACE, okmsg } = require('../../lib/device');
const webenv = require('../../lib/webenv');
const pqc = require('../../lib/pqc');
const { pgpRsaKey, loadSlots, RSA_2048_BYTES } = require('../../lib/pgp-rsa');

/* done_process_packets()'s end-of-priming print - the press window opens here. */
const PRIMED = /Encrypted Buffer/g;

const USER = { name: 'Kit', email: 'kit@example.com' };
const SENDER = { name: 'Sender', email: 'sender@example.com' };

const PLAINTEXT = 'the pages that no kit has driven';

describe('the web app\'s encrypt and decrypt pages, at the library tier', {
  state: 'initialized',
  requires: ['crypto', 'webapp-lib'],
  timeoutMs: 300000,
}, () => {
  const verbose = () => (process.env.OKT_WEBLIB_VERBOSE === 'yes' ? console : undefined);

  /**
   * The library, connected, with the two things the PAGES supply rather than the
   * library: `getKey` (plugin.js's, reduced to its armored-input branch, since
   * nothing here fetches from keybase or protonmail) and `request_pgp_pubkey`,
   * which is how the decrypt page tells `auth_decrypt` which ESK packet is ours.
   *
   * `usevirtru` is passed as UNDEFINED and that matters: plugin.js's `pgp()`
   * forwards an absent argument, and `usevirtru != null` is TRUE for `false`, so
   * passing `false` here would arm a branch no page ever arms.
   */
  async function connect(device, armored, { signal }) {
    const imports = webenv.create(device, { signal, console: verbose() });
    const api = webenv.load(imports, 'onlykey-api.js');
    await new Promise((resolve, reject) => {
      api.connect((err) => (err ? reject(new Error(String(err))) : resolve()));
    });
    api.getKey = (value) => Promise.resolve(value);
    api.request_pgp_pubkey = () => Promise.resolve({ value: armored, on_error: () => {} });

    const pgp = webenv.load(imports, 'onlykey-pgp.js')(api).api();
    return { api, pgp, openpgp: webenv.openpgp() };
  }

  /** Watch the status line the pages put on their button - see doPinTimer(). */
  function watchChallenge(pgp) {
    const seen = [];
    pgp.on('status', (message) => {
      const m = /challenge code ([0-9,]+) on OnlyKey/.exec(String(message));
      if (m) seen.push(m[1].split(',').map(Number));
    });
    return seen;
  }

  /*
   * Both entry points are `async` AND callback-style, and the two disagree: the
   * callback is the page's only channel, but the promise is where a throw inside
   * the library lands. The pages ignore it, so a fault in there reaches a browser
   * as an unhandled rejection in the console and a button that never changes. A
   * test that ignored it the same way would report the run as aborted rather than
   * failing the test that caused it, so both are wired here.
   */
  const settle = (promise, reject) => {
    if (promise && typeof promise.catch === 'function') promise.catch(reject);
  };

  const encryptWith = (pgp, to, from, message) => new Promise((resolve, reject) => {
    settle(pgp.startEncryption(to, from, message, null, (err, data) => (
      err ? reject(new Error(String(err))) : resolve(data)
    )), reject);
  });

  const decryptWith = (pgp, signer, mine, message) => new Promise((resolve, reject) => {
    settle(pgp.startDecryption(signer, mine, message, null, (err, data) => (
      err ? reject(new Error(String(err))) : resolve(data)
    )), reject);
  });

  /*
   * The api object a page hands the PGP layer when no device is wanted.
   *
   * `getKey` is plugin.js's, down to the branch that matters here: an empty box
   * resolves to FALSE rather than to an empty string, which is what turns the
   * dead guards below into a hang instead of an error.
   */
  const pagelessApi = () => ({
    getKey: (url) => Promise.resolve(url || false),
  });

  it('Encrypt Only produces a message openpgp.js opens, and never touches the device',
    async ({ device, assert, log }) => {
      /*
       * SURFACE: none - and that is the assertion. Of the encrypt page's three
       * modes only Encrypt Only avoids the device entirely, which makes it the
       * cheapest "did we break encrypt" check there is: it runs with nothing
       * plugged in. The library is built here against a STUB api and a null
       * device, so anything that reached for the device would fail rather than
       * quietly work.
       */
      const openpgp = webenv.openpgp();
      const recipient = await pgpRsaKey(openpgp, [SENDER]);

      const primed = device.log.count(PRIMED);

      const imports = webenv.create(null, {});
      const pgp = webenv.load(imports, 'onlykey-pgp.js')(pagelessApi()).api();
      pgp._$mode('Encrypt Only');

      const armored = await encryptWith(pgp, recipient.armored, '', PLAINTEXT);
      log(`${String(armored).length} characters of armored message`);
      assert.match(String(armored), /^-----BEGIN PGP MESSAGE-----/,
        'startEncryption did not produce an armored PGP message');

      /* The oracle: a library that has never seen this device opens it with the
       * private half. Self-consistency would have proved nothing here, because
       * kbpgp wrote the message and kbpgp would happily read its own mistakes. */
      const opened = await openpgp.decrypt({
        message: await openpgp.readMessage({ armoredMessage: String(armored) }),
        decryptionKeys: recipient.privateKey,
      });
      assert.equal(opened.data, PLAINTEXT,
        'openpgp.js recovered something other than the plaintext that went in');

      assert.equal(device.log.count(PRIMED), primed,
        'Encrypt Only primed a confirmation on the device - this mode must reach no device at all');
    });

  it('startEncryption\'s empty-argument guards are UNREACHABLE, and the mode hangs instead',
    async ({ device, assert, log }) => {
      /*
       * SURFACE: none. Pinned as it ships, and written to FAIL when it is fixed.
       *
       * startEncryption opens with two guards:
       *
       *     if (to_pgpkeys.value == "" && ...) { _api.emit("error", ...); return; }
       *     if (from_signer.value == "" && ...) { ... }
       *
       * but both pages pass STRINGS - `page.urlinputbox.value`, already
       * dereferenced - so `.value` is undefined on arrival and `undefined == ""`
       * is false. Neither guard can fire. startDecryption's equivalents test the
       * string itself and are fine, which is what makes this a slip rather than a
       * convention.
       *
       * What happens instead is worse than a missing message. The empty string
       * reaches `keyStore.loadPublic("")`, which emits its own error and RETURNS
       * without resolving its promise - so the `await` above it never settles,
       * the callback never fires, and the page's output box never fills. That
       * exact symptom - "the box never fills" - is also what a WebAuthn rpId
       * mistake looks like from the browser, which is why it is worth naming
       * here where there is no browser to blame.
       */
      const primed = device.log.count(PRIMED);

      const imports = webenv.create(null, {});
      const pgp = webenv.load(imports, 'onlykey-pgp.js')(pagelessApi()).api();
      pgp._$mode('Encrypt Only');

      const errors = [];
      pgp.on('error', (message) => errors.push(String(message)));

      const settled = { done: false };
      encryptWith(pgp, '', '', PLAINTEXT).then(
        () => { settled.done = true; }, () => { settled.done = true; }
      );

      /* Bounded, because the point is that it never finishes: a race rather than
       * a wait, so this costs two seconds instead of a watchdog. */
      await device.sleep(2000);

      log(`errors emitted: ${JSON.stringify(errors)}`);
      assert.equal(settled.done, false,
        'startEncryption called back with an empty recipient - the .value guards now fire, ' +
        'so this pin can be replaced by an assertion about WHICH error came back');
      /*
       * WHICH message, not merely that one arrived - the two are one word apart
       * and they come from opposite sides of the guard. The guard says "...to
       * encrypt :(" and returns cleanly; loadPublic says "...pgp key :(" and
       * abandons the promise. Matching loosely would let a fixed guard pass this
       * test while the first assertion caught it, which is a confusing way to
       * report a fix.
       */
      assert.ok(errors.includes("I need recipient's public pgp key :("),
        `the empty input was reported as ${JSON.stringify(errors)}, not by loadPublic - ` +
        'if this is now the guard\'s "...to encrypt :(" then the guard fires and this pin is done');
      assert.equal(device.log.count(PRIMED), primed, 'a failed encrypt reached the device');
    });

  it('Sign Only signs on RSA slot 2, and openpgp.js verifies the signature',
    async ({ device, assert, signal, log }) => {
      /*
       * SURFACE: FIDO for the whole operation, vendor for the key and its
       * modulus, console for the press window and the hashed packet.
       *
       * The first time this kit has driven a PGP signature through the shipped
       * library. The device holds only P and Q; openpgp.js holds the whole key
       * and has never spoken to the device - so a signature it verifies proves
       * the device recomputed the private exponent correctly AND that kbpgp
       * assembled a packet a standard implementation accepts.
       */
      const openpgp = webenv.openpgp();
      const key = await pgpRsaKey(openpgp, [USER]);
      assert.bytes(key.primary.e, Buffer.from([0x01, 0x00, 0x01]),
        'the device hardcodes E to 65537; a key with any other exponent stores fine ' +
        'and then signs with a D it does not have');

      await loadSlots(device, key, ['sign'], { signal, assert, log });

      const { pgp } = await connect(device, key.armored, { signal });
      pgp._$mode('Sign Only');
      const challenges = watchChallenge(pgp);

      device.log.clear();
      const armored = await pqc.confirmFromConsole(device,
        () => encryptWith(pgp, '', key.armored, PLAINTEXT), { signal });

      assert.match(String(armored), /^-----BEGIN PGP MESSAGE-----/,
        'Sign Only did not produce an armored PGP message');

      /*
       * THE ORACLE. openpgp.js looks the signature up by the issuer key id kbpgp
       * patched in - `onlykey.custom_keyid`, which is the primary of the key the
       * page was given - and verifies it against the public half of exactly the
       * key whose factors are in slot 2.
       */
      const verified = await openpgp.verify({
        message: await openpgp.readMessage({ armoredMessage: String(armored) }),
        verificationKeys: key.publicKey,
        expectSigned: true,
        format: 'utf8',
      });
      assert.equal(verified.data, PLAINTEXT, 'the signed message carries different text');
      assert.equal(await verified.signatures[0].verified, true,
        'openpgp.js could not verify a signature the device made with the key in RSA slot 2');

      /*
       * The second oracle, and it is nearly free. The library computes the three
       * challenge digits itself - get_pin() takes bytes 0, 15 and 31 of SHA256
       * over the payload, mod 6, plus one - and prints them for a human to read
       * off the page. The device prints the bytes it hashed. They have to agree,
       * or the digits shown to a user are not the ones the device wants and the
       * feature is unusable by hand even when a scripted press makes it pass.
       */
      const packet = pqc.packetFromConsole(device);
      assert.ok(packet, 'the device never dumped the packet it hashed');
      assert.equal(packet.length, 64,
        `kbpgp signs a SHA-512 digest, so the device should have hashed 64 bytes, not ${packet.length}`);
      assert.ok(challenges.length >= 1, 'the library never announced a challenge code');
      log(`library said ${challenges[0]}, device hashed ${packet.length} bytes`);
      assert.equal(challenges[0].join(','), pqc.challengeDigitsFor(packet).join(','),
        'the digits the page shows a user are not the ones the device is waiting for');
    });

  it('Encrypt and Sign both seals to the recipient and signs on RSA slot 2',
    async ({ device, assert, signal, log }) => {
      /*
       * SURFACE: as above. The mode the encrypt page defaults to, and the one
       * where a mistake is quietest: a message that is encrypted but unsigned
       * still opens, so only asking openpgp.js for BOTH properties catches a
       * signature that was skipped rather than made.
       */
      const openpgp = webenv.openpgp();
      const mine = await pgpRsaKey(openpgp, [USER]);
      const recipient = await pgpRsaKey(openpgp, [SENDER]);

      await loadSlots(device, mine, ['sign'], { signal, assert, log });

      const { pgp } = await connect(device, mine.armored, { signal });
      pgp._$mode('Encrypt and Sign');

      device.log.clear();
      const armored = await pqc.confirmFromConsole(device,
        () => encryptWith(pgp, recipient.armored, mine.armored, PLAINTEXT), { signal });
      assert.match(String(armored), /^-----BEGIN PGP MESSAGE-----/,
        'Encrypt and Sign did not produce an armored PGP message');

      const opened = await openpgp.decrypt({
        message: await openpgp.readMessage({ armoredMessage: String(armored) }),
        decryptionKeys: recipient.privateKey,
        verificationKeys: mine.publicKey,
        expectSigned: true,
      });
      assert.equal(opened.data, PLAINTEXT, 'the recipient recovered different text');
      assert.equal(await opened.signatures[0].verified, true,
        'the message decrypted but its signature does not verify - the device signed with ' +
        'the wrong key, or nothing signed it at all');
    });

  it('Decrypt Only recovers a message sealed to the RSA key in slot 1',
    async ({ device, assert, signal, log }) => {
      /*
       * SURFACE: FIDO for the operation, vendor for the key, console for the
       * press window. The decrypt half of the pair, and the one that crosses the
       * keyhandle boundary: a PKCS#1 v1.5 ciphertext for RSA-2048 is a whole
       * modulus, 256 bytes, so u2fSignBuffer sends it as 228 + 28 - two
       * keyhandles with an advancing opt3. 23-rsa-tunnel proves the firmware
       * keeps both; this proves the LIBRARY sends both.
       *
       * The message is sealed by openpgp.js to the encryption SUBKEY, which is
       * the half in slot 1. If the library had the two slots the other way round
       * the device would decrypt with the signing key and hand back noise.
       */
      const openpgp = webenv.openpgp();
      const key = await pgpRsaKey(openpgp, [USER]);

      await loadSlots(device, key, ['decrypt'], { signal, assert, log });

      const message = await openpgp.encrypt({
        message: await openpgp.createMessage({ text: PLAINTEXT }),
        encryptionKeys: key.publicKey,
        format: 'armored',
      });
      assert.match(String(message), /^-----BEGIN PGP MESSAGE-----/, 'no message to decrypt');

      const { pgp } = await connect(device, key.armored, { signal });
      pgp._$mode('Decrypt Only');

      device.log.clear();
      const literals = await pqc.confirmFromConsole(device,
        () => decryptWith(pgp, '', key.armored, String(message)), { signal });

      assert.ok(literals && literals.length >= 1, 'startDecryption returned nothing to read');
      assert.equal(literals[0].toString(), PLAINTEXT,
        'the device did not recover the session key sealed to its own subkey');

      /* The request crossed a keyhandle boundary, which is the thing about this
       * mode that a signature never exercises. The device's own dump is the only
       * place the accumulated length is visible. */
      const packet = pqc.packetFromConsole(device);
      log(`device accumulated ${packet && packet.length} bytes of ciphertext`);
      assert.equal(packet && packet.length, RSA_2048_BYTES,
        `the device hashed ${packet && packet.length} bytes of a ${RSA_2048_BYTES}-byte ` +
        'ciphertext - a short count means the library dropped an early keyhandle');
    });

  it('Decrypt and Verify recovers the text and names the sender', async ({
    device, assert, signal, log,
  }) => {
    /*
     * SURFACE: as above. The mode the decrypt page defaults to, and the only one
     * that puts a THIRD key in play - the sender's, verified host-side by kbpgp
     * with no device involvement. It runs `unbox` in STRICT mode, unlike Decrypt
     * Only, so a message whose signature does not check fails the whole call
     * rather than arriving unsigned.
     */
    const openpgp = webenv.openpgp();
    const key = await pgpRsaKey(openpgp, [USER]);
    const sender = await pgpRsaKey(openpgp, [SENDER]);

    await loadSlots(device, key, ['decrypt'], { signal, assert, log });

    const message = await openpgp.encrypt({
      message: await openpgp.createMessage({ text: PLAINTEXT }),
      encryptionKeys: key.publicKey,
      signingKeys: sender.privateKey,
      format: 'armored',
    });

    const { pgp } = await connect(device, key.armored, { signal });
    pgp._$mode('Decrypt and Verify');

    const statuses = [];
    pgp.on('status', (m) => statuses.push(String(m)));

    device.log.clear();
    const literals = await pqc.confirmFromConsole(device,
      () => decryptWith(pgp, sender.armored, key.armored, String(message)), { signal });

    assert.ok(literals && literals.length >= 1, 'startDecryption returned nothing to read');
    assert.equal(literals[0].toString(), PLAINTEXT, 'the recovered text is not what was sealed');

    /*
     * Who signed it, which is the entire difference between this mode and
     * Decrypt Only - and the library reports it only on the status line, which
     * is exactly what the page renders. `get_data_signer()` returning null is
     * how an unsigned message looks, and it produces a different sentence.
     */
    const signed = statuses.filter((s) => /Signed by/.test(s));
    log(`status lines: ${JSON.stringify(statuses.slice(-2))}`);
    assert.ok(signed.length >= 1,
      `the library never reported a signer: ${JSON.stringify(statuses)}`);
    assert.includes(signed[signed.length - 1], SENDER.email.split('@')[0],
      'the library named a different signer than the key that signed the message');
  });
});
