/*
 * TC-11, phase one: put a composite PGP-PQC key ON the device, and prove it is
 * the key that went in.
 *
 * This is the prerequisite the browser tier cannot supply for itself.
 * `OKSETPRIV` is not reachable over the WebAuthn transport at all - confirmed
 * by direct firmware read, and recorded in composite_pgp.js's own comments - so
 * a composite key can only be loaded by a client that speaks the vendor
 * interface. That is `onlykey-cli setpqc`, and therefore section 2, and
 * therefore this file has to exist before the pgp-pqc page can be tested at all.
 *
 * Verifying the load is the interesting part, because the device will not tell
 * you. okpqc.h says it plainly: okcrypto_getpubkey() has no KEYTYPE_PQC_PGP
 * branch, so there is no reading the key back. The only evidence a load worked
 * is the device USING it - so this asks the device to sign, and checks the
 * signature against a public key derived from the very bytes that were sent.
 *
 * That closes the loop 06-composite-key left open. There the blob was checked
 * against the key material it was packed from; here the DEVICE's use of it is
 * checked against the same material, which is the only way to find out whether
 * the firmware reads the layout the way the web app writes it.
 */
'use strict';

const crypto = require('crypto');

const { describe, it } = require('../../lib/harness');
const { PINS } = require('../../lib/config');
const cli = require('../../lib/cli');
const webenv = require('../../lib/webenv');
const pqc = require('../../lib/pqc');

const SLOT_NAME = 'RSA1';
const SLOT_ID = 1;
const HALF_ECC = 0;

describe('loading a composite PGP-PQC key', {
  state: 'initialized',
  requires: ['crypto', 'client-access', 'webapp-lib', 'xwing-math'],
  timeoutMs: 240000,
}, () => {
  let blob = null;
  let ed25519Pub = null;

  it('generates a key to load', async ({ assert, log }) => {
    /*
     * Generated by the WEB APP's own code, deliberately. The point of loading
     * it with the CLI is that the two halves of this feature live in different
     * clients: the browser makes the key, a command line puts it on the device,
     * and neither can do the other's job. If they disagree about the layout,
     * this is where it shows.
     */
    const composite = webenv.loadPlain('composite_pgp.js');
    const generated = await composite.generateCompositeKey(webenv.openpgp(), {
      userId: { name: 'Kit', email: 'kit@example.com' },
    });

    blob = Buffer.from(generated.blob);
    assert.equal(blob.length, 160, 'the blob is not 160 bytes');

    /*
     * The public half of the Ed25519 secret at offset 0 - derived here from the
     * bytes about to be sent, not read back from anywhere. That is what makes
     * the signature check below meaningful: it can only pass if the device
     * stored, and later used, exactly these bytes.
     */
    const { ed25519 } = require('@noble/curves/ed25519.js');
    ed25519Pub = Buffer.from(ed25519.getPublicKey(blob.subarray(0, 32)));
    log(`blob ready, ed25519 public ${ed25519Pub.toString('hex').slice(0, 16)}…`);
  });

  it('loads it with onlykey-cli, in config mode', async ({ device, assert, signal }) => {
    /*
     * Config mode is required by the firmware for OKSETPRIV, and it is the KIT
     * that enters it - over its own transport, before the CLI runs. The two
     * clients are cooperating on one device here rather than competing: the kit
     * arranges the state, the CLI does the thing only it can do.
     */
    await device.unlock(PINS.primary, { signal });
    await device.enterConfigMode(PINS.primary, { signal });

    const result = await cli.run('onlykey-cli',
      ['setpqc', SLOT_NAME, blob.toString('hex')], { timeoutMs: 60000, signal });

    assert.equal(result.code, 0,
      `setpqc failed: ${result.stderr || result.stdout}`);
    assert.includes(`${result.stdout}${result.stderr}`, 'Loaded composite',
      `setpqc did not report a load: ${result.stdout}`);
  });

  it('signs with the key it was given', async ({ device, assert, signal, log }) => {
    /*
     * The only evidence available, and it has to come out of the device. The
     * Ed25519 half is asked for rather than the ML-DSA one because a 64-byte
     * signature over a known message is verifiable here in three lines, while
     * ML-DSA-65 would need the seed expanded first - a bigger claim to check
     * and a smaller one to make.
     *
     * Left config mode first: config mode is an allow-list of eleven messages
     * and OKSIGN is not among them, so signing from inside it is silently
     * dropped.
     */
    await device.restart({ signal });
    await device.unlock(PINS.primary, { signal });

    const digest = crypto.createHash('sha256').update('composite sign, from the kit').digest();

    /*
     * Three things here are not pqc.sign(), and each replaces something in it
     * that does not survive contact with a real signature.
     *
     * ONE: the challenge. A composite sign needs the three-button confirmation
     * answered, exactly as a PQC keygen does - okpqc_sign() primes on its first
     * call (`if (!CRYPTO_AUTH) { process_packets(...); return; }`) and does
     * nothing at all until CRYPTO_AUTH reaches 4. The digits hash what was
     * primed, which is the payload: [selector] + digest. lib/pqc.js already
     * computes those and times the presses off the device's own
     * "Encrypted Buffer" print.
     *
     * TWO: the read has to skip status. The device announces "UNLOCKED..." on
     * its own schedule, and a single read after OKSIGN takes whichever report
     * is first - which is how the ASCII of "UNLOCKED" turned up where a
     * signature belonged, twice, before this loop existed.
     *
     * THREE: read_bytes, not read_string. pqc.sign() returns
     * `read_string(...)[:64]`, and read_string is
     * `''.join(chr(b) for b in ... if b != 0)` - it DROPS EVERY ZERO BYTE.
     * Fine for the status strings it was written for; wrong for binary. Any
     * signature containing a 0x00 comes back short and shifted, so the failure
     * is intermittent and reads as a bad key rather than a bad read.
     * python-onlykey is read-only here, so this sends the same message itself.
     */
    const primed = Buffer.concat([Buffer.from([HALF_ECC]), digest]);
    const digits = pqc.challengeDigitsFor(primed);

    const result = await pqc.runWithConfirm(device, 'python3', ['-c', [
      'import time, binascii',
      'from onlykey.client import OnlyKey, Message',
      'ok = OnlyKey()',
      'ok.set_time(time.time())',
      `digest = binascii.unhexlify("${digest.toString('hex')}")`,
      `ok.send_large_message2(msg=Message.OKSIGN, slot_id=${SLOT_ID},`,
      `                       payload=bytes([${HALF_ECC}]) + digest)`,
      /*
       * Read until something that is not a status broadcast arrives. The device
       * announces "UNLOCKED..." on its own schedule, and a single read after
       * OKSIGN takes whichever report happens to be first - which is how the
       * ASCII of "UNLOCKED" turned up where a signature belonged. A real client
       * has the same problem; this is what it has to do about it.
       */
      'sig = None',
      'deadline = time.time() + 25',
      'while time.time() < deadline:',
      '    got = bytearray(ok.read_bytes(64, timeout_ms=2000))',
      '    if not got:',
      '        continue',
      '    text = bytes(got).decode("latin-1")',
      '    if text.startswith("UNLOCKED") or text.startswith("INITIALIZED"):',
      '        continue',
      '    if not any(got):',
      '        continue',
      '    sig = got',
      '    break',
      'print(binascii.hexlify(bytes(sig or b"")).decode())',
      'ok.close()',
    ].join('\n')], { digits, timeoutMs: 90000, signal });

    assert.equal(result.code, 0, `the device would not sign: ${result.stderr}`);

    const hex = (result.stdout.trim().split('\n').pop() || '').trim();
    assert.match(hex, /^[0-9a-f]{128}$/, `not a 64-byte signature: ${hex.slice(0, 80)}`);
    log(`device signed, ${hex.slice(0, 16)}…`);

    /*
     * The assertion the whole file is for. This verifies only if the device
     * signed with the Ed25519 secret that sat at offset 0 of the blob - which
     * means the firmware read the layout the way the web app wrote it, the CLI
     * chunked it correctly across three 57-byte messages, and the slot kept it.
     */
    const { ed25519 } = require('@noble/curves/ed25519.js');
    const ok = ed25519.verify(Buffer.from(hex, 'hex'), digest, ed25519Pub);

    assert.ok(ok, 'the signature does not verify against the key that was loaded');
  });

  it('does not sign with a key nobody loaded', async ({ assert, signal }) => {
    /*
     * The control. An empty slot that answered with something signature-shaped
     * would make the test above pass for the wrong reason, and slot 2 has never
     * been written to.
     */
    const digest = crypto.createHash('sha256').update('nothing is in slot two').digest();

    const result = await cli.run('python3', ['-c', [
      'import time, binascii',
      'from onlykey.client import OnlyKey, Message',
      'ok = OnlyKey()',
      'ok.set_time(time.time())',
      `digest = binascii.unhexlify("${digest.toString('hex')}")`,
      'try:',
      `    ok.send_large_message2(msg=Message.OKSIGN, slot_id=2, payload=bytes([${HALF_ECC}]) + digest)`,
      '    sig = bytearray(ok.read_bytes(64, timeout_ms=8000))',
      '    print("SIGNED:" + binascii.hexlify(bytes(sig)).decode())',
      'except Exception as e:',
      '    print("REFUSED:" + str(e))',
      'ok.close()',
    ].join('\n')], { timeoutMs: 60000, signal });

    assert.equal(result.code, 0, `python crashed outright: ${result.stderr}`);

    const signed = (result.stdout.match(/^SIGNED:([0-9a-f]+)$/m) || [])[1];
    if (signed) {
      const { ed25519 } = require('@noble/curves/ed25519.js');
      assert.ok(!ed25519.verify(Buffer.from(signed, 'hex'), digest, ed25519Pub),
        'an empty slot produced a signature valid under the loaded key');
    }
  });
});
